sudo: false
language: node_js
matrix:
    fast_finish: true
    allow_failures:
        - node_js: "5"
node_js:
    - "0.10"
    - "0.12"
    - "4"
    - "5"
services:
    - couchdb
env:
    global:
        - NODE_ENV=test
        - TOKEN=apptoken
        - NAME=fakeapp
        - CXX=g++-4.8
before_install:
    - travis_retry git clone git://github.com/cozy/cozy-data-system.git
    - travis_retry npm install npm@latest-2 -g
    - travis_retry npm install forever coffee-script -g
    - cd cozy-data-system
    - travis_retry npm install
    - env NAME=data-system TOKEN=token forever start -o forever-ds.log build/server.js
    - sleep 5
    - ps aux | grep server.js
    - curl http://localhost:9101/
    - coffee commands.coffee test-install fakeapp ../tests/fakeapp-package.json
    - cat forever-ds.log
    - cd ..

after_failure:
    - cat cozy-data-system/forever-ds.log
    - cat cozy-data-system/forever-ds-err.log
    - curl http://localhost:9101/
