// Generated by CoffeeScript 1.6.2
(function() {
  var Client, NotificationsHelper;

  Client = require('request-json').JsonClient;

  module.exports = NotificationsHelper = (function() {
    function NotificationsHelper(app, port) {
      this.app = app;
      if (port == null) {
        port = 9103;
      }
      this.client = new Client("http://localhost:" + port + "/");
    }

    NotificationsHelper.prototype.createTemporary = function(params, callback) {
      if (callback == null) {
        callback = function() {};
      }
      return this.client.post('notifications', params, callback);
    };

    NotificationsHelper.prototype.createOrUpdatePersistent = function(ref, params, callback) {
      if (callback == null) {
        callback = function() {};
      }
      return this.client.put("notifications/" + this.app + "/" + ref, params, callback);
    };

    NotificationsHelper.prototype.destroy = function(ref, callback) {
      if (callback == null) {
        callback = function() {};
      }
      return this.client.del("notifications/" + this.app + "/" + ref, callback);
    };

    return NotificationsHelper;

  })();

}).call(this);
